config/routes.rb
Gladiatoria::Application.routes.draw do

  resources :martial_arts

  root 'techniques#search'

    resources :techniques do

      collection do
        get :search
      end

    end

  

end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do

    attr_accessor :hit

    class_attribute :index
    class_attribute :esclient

    self.index = {}
    self.index[self.name.tableize.to_sym] = { mappings: {}, settings: {} }
    self.index[self.name.tableize.to_sym][:mappings][self.name.tableize.singularize.to_sym] = {}
    self.esclient = Elasticsearch::Client.new host: ENV['SEARCHBOX_URL']

    after_update do
      update_document
      true
    end

    after_create do
      create_document
      true
    end

    after_destroy do
      delete_document
      true
    end

    settings_default

  end

  def create_document
    self.esclient.create index: self.class.name.tableize,
                          type: self.class.name.tableize.singularize,
                            id: try(:id),
                          body: attributes
  end

  def update_document
    delete_document
    create_document
  end

  def delete_document
    self.esclient.delete index: self.class.name.tableize,
                         type: self.class.name.tableize.singularize,
                         id: try(:id)
  end

  module ClassMethods

    def settings_default
      settings index: {
        :analysis => {
          :analyzer=> {
            :index_analyzer=> {
              :tokenizer=> "standard",
              :filter=> ["standard", "my_delimiter", "lowercase", "stop", "asciifolding", "porter_stem", "my_edge"]
            },
            :search_analyzer=> {
              :tokenizer=> "standard",
              :filter=> ["standard", "lowercase", "stop", "asciifolding", "porter_stem"]
            }
          },
          :filter=> {
            :my_delimiter => {
              :type=> "word_delimiter",
              :generate_word_parts=> true,
              :catenate_words=> true,
              :catenate_numbers=> true,
              :catenate_all=> true,
              :split_on_case_change=> true,
              :preserve_original=> true,
              :split_on_numerics=> true,
              :stem_english_possessive=> true
            },
            my_edge: {
              type: 'edgeNGram', #1 to 10 letters, from the start
              min_gram: 1,
              max_gram: 10,
              side: 'front'
            }
          }
        }
      }
    end

    def mapping conf
      self.index[self.name.tableize.to_sym][:mappings][self.name.tableize.singularize.to_sym] = conf
    end
    def settings conf
      self.index[self.name.tableize.to_sym][:settings] = conf
    end

    def create_index
      self.esclient.indices.create index: self.name.tableize, body: self.index[self.name.tableize.to_sym]
    end

    def destroy_index
      self.esclient.indices.delete index: self.name.tableize
    end

    def create_documents
      documents = self.name.constantize.send(:all).map do |document|
        {
          index:  {
            _index: self.name.tableize,
            _type: self.name.tableize.singularize,
            _id: document.try(:id),
            data: document.attributes
          }
        }
      end
      self.esclient.bulk body: documents if documents.present?
    end

  end

end

app/models/martial_art.rb
class MartialArt < ActiveRecord::Base
	has_and_belongs_to_many :techniques
	validates_presence_of :name, :description
end

app/models/technique.rb
class Technique < ActiveRecord::Base

  has_and_belongs_to_many :martial_arts
  
  validates_presence_of :name, :description, :martial_arts

  include Searchable

  mapping _all: {
    auto_boost: true,
    index_analyzer: "index_analyzer",
    search_analyzer: "search_analyzer"
  },
  properties: {
    description: {
      type: "string",
      index_analyzer: "index_analyzer",
      search_analyzer: "search_analyzer"
    },
    name: {
      type: "string",
      boost: 10,
      store: true,
      index_analyzer: "index_analyzer",
      search_analyzer: "search_analyzer"
    }
  }

  def self.search query=""
    begin
      results = Technique.esclient.search index:"techniques", body:"{\"query\": {\"query_string\": {\"query\": \"#{query}\"}}}"
      ids = results["hits"]["hits"].map{ |hit| hit["_id"] }
      find ids
    rescue
      []
    end
  end  # /search

end  # /Technique

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/martial_arts_controller.rb
class MartialArtsController < ApplicationController

  respond_to :html

  before_action :set_martial_art, only: [:show, :edit, :update, :destroy]

  def index
    @martial_arts = MartialArt.all
  end

  def show
  end

  def new
    @martial_art = MartialArt.new
  end

  def edit
  end

  def create
    @martial_art = MartialArt.create martial_art_params
    respond_with @martial_art
  end

  def update
    @martial_art.update(martial_art_params)
    respond_with @martial_art

  end

  # DELETE /martial_arts/1
  # DELETE /martial_arts/1.json
  def destroy
    @martial_art.destroy
    respond_to do |format|
      format.html { redirect_to martial_arts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_martial_art
      @martial_art = MartialArt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def martial_art_params
      params.require(:martial_art).permit(:name, :description)
    end
end

app/controllers/techniques_controller.rb
class TechniquesController < ApplicationController

  respond_to :html, :json

  before_action :set_technique, only: [:show, :edit, :update, :destroy]

  def index
    @techniques = Technique.all
    respond_with @techniques
  end

  def show
  end

  def new
    @technique = Technique.new
  end

  def edit
  end

  def create
    @technique = Technique.create technique_params
    respond_with @technique
  end

  def update
    @technique.update(technique_params)
    respond_with @technique
  end

  def destroy
    @technique.destroy
    respond_with @technique
  end

  def search
    @techniques = Technique.search params[:query]
    respond_with @techniques
  end

  private
    def set_technique
      @technique = Technique.find(params[:id])
    end

    def technique_params
      params.require(:technique).permit(:name, :description, :martial_art_ids => [])
    end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Martialarts</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
</head>

<body>


<div id="topo">

  <div class="container">

    <div class="logo">
      Martial Arts
    </div>


    <ul id="menu">

      <li><%= link_to_unless_current('Início', root_path) { link_to 'Início', root_path, :class => 'ativo' } %></li>
      <li><%= link_to_unless_current('Vídeos', techniques_path ) { link_to 'Vídeos', techniques_path, :class => 'ativo' } %></li>

    </ul> <!-- /menu -->
  </div> <!-- /container -->
</div> <!-- /topo -->


<div id="conteudo">
  <div class="container">
    <%= yield %>
  </div> <!-- /container -->
</div> <!-- /conteudo -->

<div id="base">
  <div class="container">

    <!-- <ul>
      <li>
        <h1><span>Parceria</span> Jornal O Povo</h1>
        <p>O que você deseja fazer ou falar para as pessoas? O que você deseja fazer ou falar para as pessoas? O que você deseja fazer ou falar para as pessoas? </p>
      </li>
      <li>
        <h1><span>Parceria</span> Jornal O Povo</h1>
        <p>O que você deseja fazer ou falar para as pessoas? O que você deseja fazer ou falar para as pessoas? O que você deseja fazer ou falar para as pessoas? </p>
      </li>
      <li>
        <h1><span>Parceria</span> Jornal O Povo</h1>
        <p>O que você deseja fazer ou falar para as pessoas? O que você deseja fazer ou falar para as pessoas? O que você deseja fazer ou falar para as pessoas? </p>
      </li>
    </ul> -->

  </div> <!-- /container -->
</div> <!-- /base -->

<div id="ft">
  <p>

  </p>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44498001-1', 'martialarts.herokuapp.com');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/martial_arts/_form.html.erb
<%= form_for(@martial_art) do |f| %>
  <% if @martial_art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@martial_art.errors.count, "error") %> prohibited this martial_art from being saved:</h2>

      <ul>
      <% @martial_art.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit 'Cadastrar' %>
  </div>
<% end %>

app/views/martial_arts/edit.html.erb
<h1>Editing martial_art</h1>

<%= render 'form' %>

<%= link_to 'Show', @martial_art %> |
<%= link_to 'Back', martial_arts_path %>

app/views/martial_arts/index.html.erb
<h1>Artes Marciais</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @martial_arts.each do |martial_art| %>
      <tr>
        <td><%= martial_art.name %></td>
        <td><%= martial_art.description %></td>
        <td><%= link_to 'Show', martial_art %></td>
        <td><%= link_to 'Edit', edit_martial_art_path(martial_art) %></td>
        <td><%= link_to 'Destroy', martial_art, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Martial art', new_martial_art_path %>

app/views/martial_arts/new.html.erb
<h1>New martial_art</h1>

<%= render 'form' %>

<%= link_to 'Back', martial_arts_path %>

app/views/martial_arts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @martial_art.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @martial_art.description %>
</p>

<%= link_to 'Edit', edit_martial_art_path(@martial_art) %> |
<%= link_to 'Back', martial_arts_path %>

app/views/techniques/_form.html.erb
<%= form_for(@technique) do |f| %>
  <% if @technique.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@technique.errors.count, "error") %> prohibited this technique from being saved:</h2>
 
      <ul>
      <% @technique.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description,  size: "84x20" %>
  </div>
 
  <div class="field">
    <%= f.label :martial_arts %><br>
    <%= select_tag 'technique[martial_art_ids][]', options_from_collection_for_select(MartialArt.all.order(:name), "id", "name", @technique.martial_arts.map(&:id)), { :multiple => true, :size =>10 } %>
  </div>
  
  <div class="actions">
    <%= f.submit "Cadastrar" %>
  </div>
<% end %>

app/views/techniques/edit.html.erb
<h1>Editing Technique</h1>

<%= render 'form' %>

<%= link_to 'Show', @technique %> |
<%= link_to 'Back', techniques_path %>

app/views/techniques/index.html.erb
<h1>
Techniques - 
<%= link_to 'Looking for a specific Technique?', :search_techniques %>
</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @techniques.each do |technique| %>
      <tr>
        <td><%= technique.name %></td>
        <td><%= technique.description %></td>
        <td><%= link_to 'Show', technique %></td>
        <td><%= link_to 'Edit', edit_technique_path(technique) %></td>
        <td><%= link_to 'Destroy', technique, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Technique', new_technique_path %>

app/views/techniques/new.html.erb
<h1>New Technique</h1>

<%= render 'form' %>

<%= link_to 'Back', techniques_path %>

app/views/techniques/search.html.erb
<form action="/techniques/search" method="GET">
  <input name="query" type="text" />
  <button type="submit">Search</button>
</form>

<h1><span>Techniques</span></h1>
<% @techniques.each do |technique| %>

  <h2><span><%= technique.try(:name) %></span> </h2>
  <p><%= technique.try(:description) %></p>

<% end %>

app/views/techniques/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @technique.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @technique.description %>
</p>

<p>
  <strong>Martial Arts:</strong>
  <ul>
  <% @technique.martial_arts.each do |m| %>
  	<li>
  		<%= m.name %>
  	</li>
  <% end %>
  </ul>
</p>


<%= link_to 'Edit', edit_technique_path(@technique) %> |
<%= link_to 'Back', techniques_path %>